import Koenig from "./assets/Koenigsegg.png";
import gtr from "./assets/gtr.png";
import rsroyce from "./assets/rollsroyce.png";
import mgzxEcl from "./assets/MGZXexclusive.png";
import crv from "./assets/cr-v.png";
import crvB from "./assets/cr-v(brown).png";
import anRush from "./assets/allNewRush.png";
import anTerios from "./assets/allNewTerios.png";
import mgzxExc from "./assets/MGZXexcite.png";
import newMGZS from "./assets/newMGZS.png";

const cars = [
  {
    name: "Koenigsegg",
    id: 1,
    class: "Sport",
    fuel: 90,
    drive: "Manual",
    seats: 2,
    price: 99.0,
    popularity: 5,
    sr: Koenig,
    favourite: false,
  },
  {
    name: "Nissan GT-R",
    id: 2,
    class: "Sport",
    fuel: 80,
    drive: "Manual",
    seats: 2,
    price: 80.0,
    popularity: 5,
    sr: gtr,
    favourite: false,
  },
  {
    name: "Rolls-Royce",
    id: 3,
    class: "Sedan",
    fuel: 70,
    drive: "Manual",
    seats: 4,
    price: 96.0,
    popularity: 5,
    sr: rsroyce,
    favourite: false,
  },
  {
    name: "MG ZX Exclusice",
    id: 4,
    class: "Hatchback",
    fuel: 70,
    drive: "Manual",
    seats: 4,
    price: 76.0,
    popularity: 5,
    sr: mgzxEcl,
    favourite: false,
  },
  {
    name: "All New Rush",
    id: 5,
    class: "SUV",
    fuel: 70,
    drive: "Manual",
    seats: 6,
    price: 72.0,
    popularity: 1,
    sr: anRush,
    favourite: false,
  },
  {
    name: "CR-V",
    id: 6,
    class: "SUV",
    fuel: 80,
    drive: "Manual",
    seats: 6,
    price: 80.0,
    popularity: 1,
    sr: crvB,
    favourite: false,
  },
  {
    name: "All New Terios",
    id: 7,
    class: "SUV",
    fuel: 90,
    drive: "Manual",
    seats: 6,
    price: 74.0,
    popularity: 1,
    sr: anTerios,
    favourite: false,
  },
  {
    name: "CR-V",
    id: 8,
    class: "SUV",
    fuel: 80,
    drive: "Manual",
    seats: 6,
    price: 80.0,
    popularity: 1,
    sr: crv,
  },
  {
    name: "New MG ZS",
    id: 9,
    class: "SUV",
    fuel: 80,
    drive: "Manual",
    seats: 6,
    price: 80.0,
    popularity: 1,
    sr: newMGZS,
    favourite: false,
  },
  {
    name: "MG ZX Excite",
    id: 10,
    class: "Hatchback",
    fuel: 90,
    drive: "Manual",
    seats: 4,
    price: 74.0,
    popularity: 1,
    sr: mgzxExc,
    favourite: false,
  },
  {
    name: "New MG ZS",
    id: 11,
    class: "SUV",
    fuel: 70,
    drive: "Automatic",
    seats: 6,
    price: 80.0,
    popularity: 1,
    sr: newMGZS,
    favourite: false,
  },
  {
    name: "All New Rush",
    id: 12,
    class: "SUV",
    fuel: 50,
    drive: "Automatic",
    seats: 6,
    price: 80.0,
    popularity: 1,
    sr: anRush,
    favourite: false,
  },
];
export default cars;
